image: atlassian/default-image:2

pipelines:
    branches:
      feature/master1:
        - step:
            script:
              - git push --mirror git@github.com:arun-source/Lm.git
      feature/dev:
        - step:
            script:
              - git push --mirror git@github.com:arun-source/Lm.git