image: atlassian/default-image:2

pipelines:
    branches:
      feature/master1:
        - step:
            script:
              - git remote add sync git@github.com:arun-source/Lm.git
              - git checkout feature/master1
              - git pull    
              - git push sync feature/master1
      feature/dev:
        - step:
            script:
              - git remote add sync git@github.com:arun-source/Lm.git
              - git checkout feature/dev
              - git pull    
              - git push sync feature/dev