clone:
  depth: full
pipelines:
  default:
    - step:
        script:
          - echo "Deploying to production environment"
          - sudo /bin/sh ./repo/bitbucket_to_github_sync_command.sh
            