clone:
  depth: full
pipelines:
  default:
    - step:
        script:
          - echo "Deploying to production environment"
          - pipe: atlassian/ssh-run:0.2.2
            variables:
              COMMAND: './repo/bitbucket_to_github_sync_command.sh'
            