pipelines:
    branches:
      master:
           - step:
              script:
                - git remote add sync git@github.com:arun-source/Lm.git
	  feature/dev:
                - step:
                   script:
                     - git remote add sync git@github.com:arun-source/Lm.git