pipelines:
    branches:
      '**':
      - step:
          script:
            - git remote add sync git@github.com:arun-source/Lm.git
            - git checkout '**'
            - git pull    
            - git push sync '**'