clone:
  depth: full
pipelines:
  default:
    - step:
        script:
          - echo "Deploying to production environment"
          - sudo /bin/sh /home/ec2-user/repo/bitbucket_to_github_sync_command.sh
            