pipelines:
  branches:
    feature/*:
      - step:
          script:
            - git push --mirror git@github.com:arun-source/Lm.git
    master:
      - step:
          script:
          - git push --mirror git@github.com:arun-source/Lm.git
    