clone:
  depth: full
pipelines:
  default:
    - step:
        script:
          - echo "Deploying to production environment"
		  - ssh ec2-user@18.213.66.32 /home/ec2-user/repo/bitbucket_to_github_sync_command.sh
            